---
title: "HPM R learners - Summer 2020"
output: html_document
---


Last Updated `r format(Sys.Date(), format="%m/%d/%Y")`

# {.tabset}

This will be the R learners website for the summer! Most all of my resources will be posted here. 

## First meeting

#### To do
1. Topics to cover - see below
2. How these should work
    + homework?
    + lectures? 
    + in-session activities with data provided?
    + working with own data? 
3. When & how often to meet



#### Potential topics

+ Data management with the `tidyverse` package(s). Would probably suggest two weeks of this.
    + Types of variables in R -- factors are the most unique to R specifically
    + Merging, subsetting, and transposing data
    + Creating new variables
+ Working with objects in R - what are they, how, and why??? `r emo::ji("angry")`
+ Descriptive statistics in R
    + There are many, many packages - how to choose? 
    + Overview with `skimr`
    + Missing data with `naniar` package
    + Full tables with `tableone`
    + There's also `stargazer` and some others
+ Basic modeling - lm, logistic, others?
+ Other stat topics? 
+ Plotting with R - endless `ggplot2` options here! Can review all sorts of x-y plots, there are some new options for making maps. 
+ R projects, R markdown, GitHub, & GitHub pages (how I am making this website, very nice for collabs)


## Getting started

Two general options for how to access and use R

1. Use R through R studio on your actual computer
    + Download R v4.0.0 [here](http://archive.linux.duke.edu/cran/)
    + Download R studio [here](https://rstudio.com/products/rstudio/download/#download)

2. Use [rstudio.cloud](rstudio.cloud) without the commitment of installing on your computer. *disclaimer: I don't know as much / anything about this*
    + Don't have to download R software and the R studio wrapper
    + Possibly less functional for all the bells and whistles -- not sure about GitHub integration, etc. But probably just fine for learning the basics, and much less potential annoyance with installations, etc. 


## Resources

This is my own compilation of useful R tidbits that don't have a good place to live, and my go-to resources for various things in R. 


+ Tools > Global Options > General > Make sure the following things are done. Best practice for reproducible work!
    + 'restore .Rdata' is unchecked
    + saving .Rdata is set to 'Never'
    + 'always save history' is unchecked. 
+ Emojis in R markdown
    + Install by: `devtools::install_github("hadley/emo")` (need `devtools` package installed)
    + [emoji package](https://github.com/hadley/emo)
    + [Emoji search](https://emoji.muan.co/)
+ [Google it](https://twitter.com/andrewheiss/status/1263652454329208839)
+ Online resources
    + Intro to `naniar` package [here](https://allisonhorst.shinyapps.io/missingexplorer/#section-introduction)
    + *Very good* `ggplot` intro by [Andrew Heiss](https://twitter.com/andrewheiss) [here](https://datavizm20.classes.andrewheiss.com/). Also some `tidyverse` but not enough to fully understand it
    + R studio cheatsheets [here](https://rstudio.com/resources/cheatsheets/)
+ Guide for good coding in social sciences, from some economists [here](https://web.stanford.edu/~gentzkow/research/CodeAndData.pdf). R is great because you can very easily do everything they suggest, and document with Rmd, and have more than one dataset open at a time `r emo::ji("fire")`
    + automation: functions are very easy in R
    + version control: git integrates well with R
    + directories: R projects
    + keys: not specific to software (keep data stored with identifiers)
    + abstraction: functions round 2
    + documentation: R markdown, easier options than local variables. 
    
    

    
    
    